language: java

jdk:
  - openjdk11

os:
  - linux

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

branches:
  except:
    - develop
    - /^feature/\d+\.\d+$/
  only:
    - master

install: true

script:
  - docker run -d --name mongo_container -e MONGO_INITDB_ROOT_USERNAME=$MNAME -e MONGO_INITDB_ROOT_PASSWORD=$MPASS -pmongo
  - curl https://raw.githubusercontent.com/enesusta/travis-test/master/application.yml?token=$YAML_TOKEN -output src/main/resources/application.yml
  - mvn clean test -DrepoToken=$COVERALLS_TOKEN jacoco:report coveralls:report