spring:
  data:
    mongodb:
      database: mongo-rest
      uri: mongodb://${MNAME}:${MPASS}@localhost:27017

  redis:
    jedis:
      password: ${REDIS_PASSWORD}

jwt:
  secret:
    key: ${JWT_KEY}
    validity: 86400